language: go

go:
  - "1.12.x"
  - "1.13.x"

gobuild_args: "-v -tags ci"

before_script:
  - NO_VENDOR=$(find . -iname '*.go' -type f | grep -v /vendor/)
  - go get golang.org/x/tools/cmd/goimports
  - go get golang.org/x/lint/golint
  - go get github.com/mattn/goveralls
  - go get fyne.io/fyne

script:
  - test -z "$(goimports -e -d $NO_VENDOR | tee /dev/stderr)"
  - go test -tags ci -race ./...
  - go vet -tags ci ./...
  - golint -set_exit_status $(go list -tags ci)
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then exit; fi'
  - |
    set -e
    if [[ "$TRAVIS_PULL_REQUEST" == "false" && -n "$COVERALLS_TOKEN" ]]
    then
      go test -tags ci -covermode=atomic -coverprofile=coverage.out ./...
      $(go env GOPATH | awk 'BEGIN{FS=":"} {print $1}')/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken $COVERALLS_TOKEN
    fi

env:
  global:
    secure: "TXvumQle32IDF7+ZA1639IYPJkzeu1h2w7dnEiuJeLyY84o9TXIjprLmoOai0LNhzjvzXna6mw+86INzD/pS571kLxuRm/aigL+UDlM8Xhl4KZ0h7Ierf5laEdBZjMApYdzjtYhUpY0kJW7WzcJP25exn7Onkd6jxcUx3B46oeXGXldVgyWnePxFtdu7H18qT9cwjw+VVFJNZ8Fb2DPrCL5K9f4nOEl3wgtmSkks11xucLeutvAsjXffGmesvyk5kdZScepTw4AlFTAqKBsKKGBKWY4yg+1evce6DhCew/ATfqEpiihRhbaXTyNhPg2MzIqANJ4IwYKIuOV2bky6Cf8VSec2ORTW1UznLdu8B9jgPYr49vhLFIdUjNT1b8mFDDK5lANq7B3jqz63XyH+HvXc8zzjeDBGMS45S8uHRoBDWcB2wkwmYET7uqwLezG5epzQIR7eCQCRUrRtFg0NdawIClt5JkAdBMqUoZVojknKH/9h3Tnem4xD/4I2MR1G0dD5mCz1bGaiIw80Kh7ef4IYnRhikLGGY2Cl4Or29mbBEsfWoXJJNV7EejqlcDsZj1jdt4PSdF2MFJwYy3gW19TkcXtgUzWOM3eGPKOsXdHXBF7EDGL7yIkjdIilDnyuaH4mOoJIlqX2LZAZWohmaG1q/C/Gk4+sCzgXHYupqSo="

